### ISSUE TITLE
Add method to flag a cell

### ISSUE THREAD

**Issue by ServerDeveloper9447** [zWolfrost/mineswift#2]
I searched the source but didn't find any way to flag a cell. Please fix it.

**Comment by zWolfrost** [comment]
You can flag a cell by setting its `isFlag` value to true. You can see all the cell properties [here](https://github.com/zWolfrost/mineswift#minefield-cell-properties)

**Comment by ServerDeveloper9447** [comment]
Can you give me an example?
I don't understand how can I do that. Do I have to get all cells and iterate over them?
It would be easier if there's a function like `flagCell([3,4])` etc...

**Comment by zWolfrost** [comment]
If you want to flag a cell (lets take the one you have given, [3,4]), you can do either
`minefield[3][4].isFlag = true` or `minefield.cellAt([3,4]).isFlag = true`.
If i understood correctly, you might want to flag a group of them. In that case just do a loop. You might want to give me more information on that so i can help you
